travis:
  secure:
    BINSTAR_TOKEN: sryHA2Y8mv7sFWrkR89KFPoz+MHbQSnh/12SM/8mDivWECzsD+bsaEwonUh+rmineoQAsD+NThowCVz5idjho+WM2CV8hn7DfnSD3ftogb3DhrJ5auDHpKojRMLCQ2b4mbLYwpZK+blidMVIvEwXs5HoxJMfBBlqaf3YbgEBBc5I37iLBlzOiXeeHLojOgNOWhmFOJrBjGRw42F1x5BQBI6OjzHC5VY1IIzs+I6n7Tqs4O8mEcfdUtHG57UPzmHvtzExov5+b5csZMONg8/U9iEwqyvPshcqqSamJOY4E72a+asKY9j7g2U7g/fEdR2xsa7FsgQbv6gxa/QUf5d2KMxmxDCE5TREMJE69Y33fno8fcj99cj1qqCDx29Oo8sa/Vsg5GIInSIe0NF5zs/gVbxLsU8vuqydCOaLDh7LtlIkmwBbMrxm9gdYHvJLe7Pv1LwoUAzwBuMyJyTZHCeNp38S97uD8eha8HnjhRCZTQy5SftrcGxrTKkdic6T+FLwliWwTch25LNKYi63t0jIlvR0l7grVFAjTEccDfIGYfFVD0IzmnQYG5BxKrsOHhF3oOymOdNiXDeGT/kDgM1UkqmmxgCAtyrP4O5bLvcsqxTa8VhqoZDWRwfdvGO74FABD2HMiAyucHOlKwKg7JZNrlrQ9PKKmxgqIl2KoVAl+mk=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
