travis:
  secure:
    BINSTAR_TOKEN: pbb+jgU4swQzPJMSqljzTHOnOzwRUJ7TODfq97X8dBEzErKPPfudLORFa4hWL4RmYVOQNjliQJGKjlBNPHZlMm1fxyivzHlIK+gaTycr2pMqt1lstb19nhnxyrKOI6xHev3K2pMMj55d1CQWogbmasPBkAbupsE9oDFcGDz4jLQaqzNumQQElKrjL96psHf4yWJM9dvz92EpNfdq135AiGj14dl7hstm1q+CvvdF29o1B421U1/Bp5l/uUHPnRdYdL7HGBONWqgAYun+BMzqgVLt0sGqUNanIvmSf0Kb+11h+rbkogSPYiWvzY8lfqvanMWL12FcmPRV2yte8omB5QzOGJEreUDh+hwITGPZafo70JSHn0KY+CsSFIhAI/3FNZMwkytR86sD6EFQMti76ouEfbSLweFeCdly84SxzagsgWT9fL88h0MBNRkemd4nhNN+X9X+mYbiEE7lbMx/z4fP3Q8ytW51Y7nuInsGqG3ctToBe8xQbkvlInbJzHOpNN84YWCh3U9ia9Z4CQ70oD7mIGjcVCM5ifiWDuIYPXWvuX9UIu6LF8/KY/u9nZGGPuYipQBUXFZb4yY8f8IV9Gof4rVg3mRZgvlG3moYN4DmAmmvdvxPZW0aXd/QHeltsewtIYpfHrAjixjHjgIZDFF/NG+bWSDPdtaKRVQvVgE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
